<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-01-19T00:21:30 IST" name="Default suite" finished-at="2024-01-19T00:23:05 IST" duration-ms="94971">
    <groups>
    </groups>
    <test started-at="2024-01-19T00:21:30 IST" name="Default test" finished-at="2024-01-19T00:23:05 IST" duration-ms="94971">
      <class name="test.ProcessOfPaymentTest">
        <test-method is-config="true" signature="configureReport()[pri:0, instance:test.ProcessOfPaymentTest@26e356f0]" started-at="2024-01-19T00:21:30 IST" name="configureReport" finished-at="2024-01-19T00:21:30 IST" duration-ms="598" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configureReport -->
        <test-method is-config="true" signature="openApp()[pri:0, instance:test.ProcessOfPaymentTest@26e356f0]" started-at="2024-01-19T00:21:30 IST" name="openApp" finished-at="2024-01-19T00:21:39 IST" duration-ms="8932" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method signature="verifyThePaymentProcess()[pri:0, instance:test.ProcessOfPaymentTest@26e356f0]" started-at="2024-01-19T00:21:39 IST" name="verifyThePaymentProcess" finished-at="2024-01-19T00:23:02 IST" duration-ms="82652" status="FAIL">
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index 0 out of bounds for length 0]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
at java.base/java.util.Objects.checkIndex(Objects.java:361)
at java.base/java.util.ArrayList.get(ArrayList.java:427)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementListHandler.invoke(LocatingElementListHandler.java:39)
at jdk.proxy2/jdk.proxy2.$Proxy18.get(Unknown Source)
at pom.CartPage.getCartAmount(CartPage.java:69)
at test.ProcessOfPaymentTest.verifyThePaymentProcess(ProcessOfPaymentTest.java:96)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyThePaymentProcess -->
        <test-method is-config="true" signature="addTestStatus(org.testng.ITestResult)[pri:0, instance:test.ProcessOfPaymentTest@26e356f0]" started-at="2024-01-19T00:23:03 IST" name="addTestStatus" finished-at="2024-01-19T00:23:03 IST" duration-ms="14" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyThePaymentProcess status=FAILURE method=ProcessOfPaymentTest.verifyThePaymentProcess()[pri:0, instance:test.ProcessOfPaymentTest@26e356f0] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addTestStatus -->
        <test-method is-config="true" signature="publishReports()[pri:0, instance:test.ProcessOfPaymentTest@26e356f0]" started-at="2024-01-19T00:23:03 IST" name="publishReports" finished-at="2024-01-19T00:23:05 IST" duration-ms="2022" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- publishReports -->
      </class> <!-- test.ProcessOfPaymentTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
